import type { ElementType } from "react";
import {
  Briefcase,
  Building2,
  Cpu,
  DollarSign,
  FileText,
  Gavel,
  Headphones,
  Heart,
  Landmark,
  Search,
  Shield,
  ShieldCheck,
  TrendingUp,
  Truck,
  User,
} from "lucide-react";

export interface UseCaseCard {
  href: string;
  icon: ElementType;
  label: string;
  title: string;
  tagline: string;
  entityExamples: string[];
  thenQuestion: string;
  accent: string;
  accentBg: string;
  accentBorder: string;
  /** Skill slugs that activate this use case. */
  skills: string[];
}

export const USE_CASES: UseCaseCard[] = [
  {
    href: "/compliance",
    icon: ShieldCheck,
    label: "Compliance",
    title: "Vendor risk & compliance",
    tagline: "Version control for vendor risk profiles",
    entityExamples: ["vendor", "assessment", "screening", "questionnaire"],
    thenQuestion: "What did we know about this vendor when we approved them?",
    accent: "text-amber-600 dark:text-amber-400",
    accentBg: "bg-amber-500/5",
    accentBorder: "border-amber-500/20",
    skills: ["remember-email", "store-data"],
  },
  {
    href: "/crm",
    icon: Building2,
    label: "CRM",
    title: "Next-generation CRM",
    tagline: "The state layer for AI-native CRM platforms",
    entityExamples: ["contact", "deal", "account", "engagement"],
    thenQuestion: "Who should I loop in on the Meridian renewal?",
    accent: "text-emerald-600 dark:text-emerald-400",
    accentBg: "bg-emerald-500/5",
    accentBorder: "border-emerald-500/20",
    skills: ["remember-email", "remember-contacts"],
  },
  {
    href: "/contracts",
    icon: FileText,
    label: "Contracts",
    title: "Contract lifecycle management",
    tagline: "Version control for every clause, amendment, and obligation",
    entityExamples: ["contract", "clause", "amendment", "obligation"],
    thenQuestion: "What were the terms when we signed? What changed in amendment 3?",
    accent: "text-indigo-600 dark:text-indigo-400",
    accentBg: "bg-indigo-500/5",
    accentBorder: "border-indigo-500/20",
    skills: ["store-data", "query-memory"],
  },
  {
    href: "/diligence",
    icon: Search,
    label: "Due Diligence",
    title: "M&A and investment diligence",
    tagline: "Know exactly what was known when the decision was made",
    entityExamples: ["target company", "finding", "red flag", "assessment"],
    thenQuestion: "What did we know about the target when the IC voted?",
    accent: "text-sky-600 dark:text-sky-400",
    accentBg: "bg-sky-500/5",
    accentBorder: "border-sky-500/20",
    skills: ["store-data", "query-memory"],
  },
  {
    href: "/portfolio",
    icon: TrendingUp,
    label: "Portfolio",
    title: "Portfolio monitoring",
    tagline: "Versioned state for every portfolio company and LP commitment",
    entityExamples: ["portfolio company", "valuation", "milestone", "LP commitment"],
    thenQuestion: "What was the valuation when we made the follow-on?",
    accent: "text-violet-600 dark:text-violet-400",
    accentBg: "bg-violet-500/5",
    accentBorder: "border-violet-500/20",
    skills: ["store-data", "query-memory"],
  },
  {
    href: "/cases",
    icon: Gavel,
    label: "Case Management",
    title: "Legal & investigation cases",
    tagline: "Reconstruct what was known at any point in a case timeline",
    entityExamples: ["case", "evidence", "filing", "party"],
    thenQuestion: "What evidence was available when we filed the motion?",
    accent: "text-cyan-600 dark:text-cyan-400",
    accentBg: "bg-cyan-500/5",
    accentBorder: "border-cyan-500/20",
    skills: ["store-data", "query-memory"],
  },
  {
    href: "/financial-ops",
    icon: DollarSign,
    label: "Financial Ops",
    title: "Financial operations & reconciliation",
    tagline: "Deterministic state for every ledger entry and reconciliation",
    entityExamples: ["transaction", "reconciliation", "ledger", "invoice"],
    thenQuestion: "Did this liability exist in our books on the audit date?",
    accent: "text-teal-600 dark:text-teal-400",
    accentBg: "bg-teal-500/5",
    accentBorder: "border-teal-500/20",
    skills: ["remember-finances"],
  },
  {
    href: "/procurement",
    icon: Briefcase,
    label: "Procurement",
    title: "Procurement & sourcing",
    tagline: "Full audit trail for bids, approvals, and supplier decisions",
    entityExamples: ["supplier", "bid", "purchase order", "approval"],
    thenQuestion: "What were the competing bids when we selected this supplier?",
    accent: "text-orange-600 dark:text-orange-400",
    accentBg: "bg-orange-500/5",
    accentBorder: "border-orange-500/20",
    skills: ["store-data", "query-memory"],
  },
  {
    href: "/agent-auth",
    icon: Shield,
    label: "Agent Auth",
    title: "Agent authorization & governance",
    tagline: "Versioned policy state, consent timelines, delegation provenance, and DAO governance lineage",
    entityExamples: [
      "auth_decision",
      "consent_grant",
      "delegation_chain",
      "policy_evaluation",
      "governance_vote",
    ],
    thenQuestion:
      "Was this agent authorized for this action at this time, and under which policy or governance decision?",
    accent: "text-blue-600 dark:text-blue-400",
    accentBg: "bg-blue-500/5",
    accentBorder: "border-blue-500/20",
    skills: ["store-data"],
  },
  {
    href: "/healthcare",
    icon: Heart,
    label: "Healthcare",
    title: "Healthcare operations",
    tagline: "Versioned clinical state, authorization lifecycles, and care plan lineage",
    entityExamples: ["patient", "encounter", "care_plan", "authorization"],
    thenQuestion: "What was known about this patient when the agent recommended the dosage change?",
    accent: "text-rose-600 dark:text-rose-400",
    accentBg: "bg-rose-500/5",
    accentBorder: "border-rose-500/20",
    skills: ["store-data", "query-memory"],
  },
  {
    href: "/government",
    icon: Landmark,
    label: "Government",
    title: "Public sector & GovTech",
    tagline: "Policy-version-bound determinations and inter-agency evidence provenance",
    entityExamples: ["determination", "policy_version", "applicant", "case_record"],
    thenQuestion: "Under which policy version was this eligibility determined?",
    accent: "text-slate-600 dark:text-slate-400",
    accentBg: "bg-slate-500/5",
    accentBorder: "border-slate-500/20",
    skills: ["store-data", "query-memory"],
  },
  {
    href: "/customer-ops",
    icon: Headphones,
    label: "Customer Ops",
    title: "Support & CX operations",
    tagline: "Routing rationale, escalation chains, and interaction-level provenance",
    entityExamples: ["ticket", "routing_decision", "interaction", "escalation"],
    thenQuestion: "Why was this ticket routed to billing instead of infrastructure?",
    accent: "text-pink-600 dark:text-pink-400",
    accentBg: "bg-pink-500/5",
    accentBorder: "border-pink-500/20",
    skills: ["store-data", "query-memory"],
  },
  {
    href: "/logistics",
    icon: Truck,
    label: "Logistics",
    title: "Logistics & supply chain",
    tagline: "Constraint snapshots, routing provenance, and inventory position history",
    entityExamples: ["shipment", "route_decision", "inventory_snapshot", "carrier_commitment"],
    thenQuestion: "What constraints did the routing agent evaluate when it chose this carrier?",
    accent: "text-lime-600 dark:text-lime-400",
    accentBg: "bg-lime-500/5",
    accentBorder: "border-lime-500/20",
    skills: ["store-data", "query-memory"],
  },
  {
    href: "/personal-data",
    icon: User,
    label: "Personal Data",
    title: "Personal agent state",
    tagline: "Versioned memory for health, finance, habits, and goals across every AI tool",
    entityExamples: ["workout", "transaction", "health_metric", "habit", "goal"],
    thenQuestion: "How has my bench press progressed, and what was my spending rate when I bought the car?",
    accent: "text-violet-600 dark:text-violet-400",
    accentBg: "bg-violet-500/5",
    accentBorder: "border-violet-500/20",
    skills: ["remember-email", "remember-finances", "remember-contacts", "remember-calendar"],
  },
  {
    href: "/trading",
    icon: TrendingUp,
    label: "Trading",
    title: "Autonomous trading agents",
    tagline:
      "Reconstructable decision chains for multi-agent trading systems, including the trades the agent passed on",
    entityExamples: [
      "trade_decision",
      "pass_decision",
      "strategy",
      "analysis",
      "risk_state",
      "portfolio_snapshot",
    ],
    thenQuestion:
      "Why did the agent pass on this trade, and what did each analyst recommend when it did?",
    accent: "text-emerald-600 dark:text-emerald-400",
    accentBg: "bg-emerald-500/5",
    accentBorder: "border-emerald-500/20",
    skills: ["store-data", "query-memory"],
  },
  {
    href: "/crypto-engineering",
    icon: Cpu,
    label: "Crypto engineering",
    title: "AI-assisted crypto & security-sensitive engineering",
    tagline: "Agent-session replay, review-cost reduction, and bounty-report provenance for codebases with a real stakes ceiling",
    entityExamples: ["agent_session", "commit", "review", "security_finding", "bounty_report"],
    thenQuestion: "Which agent wrote this commit, what did it verify, what did it skip, and why?",
    accent: "text-orange-600 dark:text-orange-400",
    accentBg: "bg-orange-500/5",
    accentBorder: "border-orange-500/20",
    skills: ["remember-codebase", "store-data"],
  },
];
