/**
 * Integration tests for the `contains_word` snapshot filter operator (#1966).
 *
 * `contains` is a raw case-insensitive SUBSTRING match, which produces the
 * false positives catalogued in the issue: `title contains "CTO"` matches
 * "director"/"doctor", "COO" matches "coordinator", "CRO" matches "microsoft",
 * and organization "Care" matches "Careers" / "Fit" matches "Profit".
 *
 * `contains_word` matches only whole tokens delimited by punctuation or
 * whitespace.
 *
 * These run on the DEFAULT local SQLite lane (unlike
 * tests/integration/entity_queries.test.ts, which is Postgres-only and excluded
 * without RUN_REMOTE_TESTS=1) because the operator is implemented as SQL
 * generated by the SQLite adapter — a mock-based unit test would assert the
 * shape of the call, not that the matching semantics are actually correct.
 */
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { db, getServiceRoleClient } from "../../src/db.js";
import { queryEntities } from "../../src/services/entity_queries.js";

const serviceRoleClient = getServiceRoleClient();

describe("queryEntities snapshot_filters contains_word (#1966)", () => {
  const testUserId = "contains-word-1966-user";
  const testEntityIds: string[] = [];

  async function cleanupEntities() {
    if (testEntityIds.length === 0) return;
    await db.from("entity_snapshots").delete().in("entity_id", testEntityIds);
    await db.from("entities").delete().in("id", testEntityIds);
    testEntityIds.length = 0;
  }

  async function createEntity(
    id: string,
    entityType: string,
    canonicalName: string,
    snapshot: Record<string, unknown>
  ) {
    const now = new Date().toISOString();
    await serviceRoleClient.from("entities").insert({
      id,
      user_id: testUserId,
      entity_type: entityType,
      canonical_name: canonicalName,
    });
    testEntityIds.push(id);
    await serviceRoleClient.from("entity_snapshots").upsert({
      entity_id: id,
      user_id: testUserId,
      entity_type: entityType,
      schema_version: "1.0",
      canonical_name: canonicalName,
      snapshot,
      provenance: {},
      observation_count: 1,
      last_observation_at: now,
      computed_at: now,
    });
  }

  /** Seed one contact per title and return the matching canonical names. */
  async function seedTitles(titles: string[]) {
    let i = 0;
    for (const title of titles) {
      await createEntity(`ent_cw_${i}`, "contact", `person_${i}`, { title });
      i += 1;
    }
  }

  async function titlesMatching(op: "contains" | "contains_word", value: string) {
    const result = await queryEntities({
      userId: testUserId,
      entityType: "contact",
      snapshotFilters: { title: { op, value } },
      limit: 100,
    });
    return result.map((e) => e.snapshot.title as string).sort();
  }

  beforeEach(async () => {
    await cleanupEntities();
  });

  afterEach(async () => {
    await cleanupEntities();
  });

  describe("excludes the documented false positives", () => {
    it('"CTO" does not match "director" or "doctor"', async () => {
      await seedTitles(["Director of Engineering", "Doctor of Medicine", "CTO & Co-founder"]);

      expect(await titlesMatching("contains_word", "CTO")).toEqual(["CTO & Co-founder"]);
    });

    it('"COO" does not match "coordinator"', async () => {
      await seedTitles(["Project Coordinator", "COO"]);

      expect(await titlesMatching("contains_word", "COO")).toEqual(["COO"]);
    });

    it('"CRO" does not match "microsoft"', async () => {
      await seedTitles(["Engineer at Microsoft", "CRO, Revenue"]);

      expect(await titlesMatching("contains_word", "CRO")).toEqual(["CRO, Revenue"]);
    });

    it('"Care" does not match "Careers"', async () => {
      await seedTitles(["Careers Page Owner", "Care Team Lead"]);

      expect(await titlesMatching("contains_word", "Care")).toEqual(["Care Team Lead"]);
    });

    it('"Fit" does not match "Profit"', async () => {
      await seedTitles(["Head of Profit Centers", "Fit Coach"]);

      expect(await titlesMatching("contains_word", "Fit")).toEqual(["Fit Coach"]);
    });

    it("does not match a term that is a prefix of a longer word (CTOs)", async () => {
      await seedTitles(["CTOs Network Member", "VP, CTO"]);

      expect(await titlesMatching("contains_word", "CTO")).toEqual(["VP, CTO"]);
    });
  });

  describe("includes true whole-word matches", () => {
    it("matches across punctuation and position variants", async () => {
      const trueMatches = [
        "CTO",
        "CTO & Co-founder",
        "VP, CTO",
        "Acme/CTO",
        "Head of Eng (CTO)",
        "Interim CTO",
      ];
      await seedTitles([...trueMatches, "Director", "Doctor", "Coordinator"]);

      expect(await titlesMatching("contains_word", "CTO")).toEqual([...trueMatches].sort());
    });

    it("is case-insensitive for ASCII terms", async () => {
      await seedTitles(["cto", "CTO", "Cto"]);

      expect(await titlesMatching("contains_word", "cto")).toEqual(["CTO", "Cto", "cto"]);
      expect(await titlesMatching("contains_word", "CTO")).toEqual(["CTO", "Cto", "cto"]);
    });

    it("matches a multi-word term as an adjacent token sequence", async () => {
      await seedTitles(["Chief Technology Officer", "Chief Revenue Officer"]);

      expect(await titlesMatching("contains_word", "Chief Technology Officer")).toEqual([
        "Chief Technology Officer",
      ]);
    });
  });

  describe("contains remains backward compatible (#1966 regression guard)", () => {
    it("still performs a raw substring match, including the false positives", async () => {
      await seedTitles(["Director of Engineering", "Doctor of Medicine", "CTO & Co-founder"]);

      // This is the pre-existing (surprising) behavior. It must NOT change:
      // existing callers depend on substring semantics.
      expect(await titlesMatching("contains", "CTO")).toEqual([
        "CTO & Co-founder",
        "Director of Engineering",
        "Doctor of Medicine",
      ]);
    });

    it("still matches mid-word substrings", async () => {
      await seedTitles(["Careers Page Owner", "Head of Profit Centers"]);

      expect(await titlesMatching("contains", "Care")).toEqual(["Careers Page Owner"]);
      expect(await titlesMatching("contains", "Fit")).toEqual(["Head of Profit Centers"]);
    });
  });

  describe("security: LIKE metacharacters cannot act as wildcards", () => {
    it("does not treat % in the search term as a wildcard", async () => {
      await seedTitles(["CTO", "100% Remote"]);

      // A bare "%" would match EVERYTHING if wildcards leaked through.
      expect(await titlesMatching("contains_word", "%")).toEqual([]);
    });

    it("does not treat _ in the search term as a single-char wildcard", async () => {
      await seedTitles(["CTO", "Head_of_Data"]);

      // "_TO" would match "CTO" if _ acted as a single-character wildcard.
      expect(await titlesMatching("contains_word", "_TO")).toEqual([]);
    });

    it("does not error or over-match on quote characters in the term", async () => {
      await seedTitles(["O'Brien", "CTO"]);

      // Must not throw (SQL injection guard) and must not over-match.
      expect(await titlesMatching("contains_word", "O'Brien")).toEqual([]);
    });
  });

  describe("documented limitation: separators inside the term", () => {
    it("a term containing a separator matches nothing (fails closed, never over-matches)", async () => {
      await seedTitles(["100% Remote", "O'Brien", "Head_of_Data"]);

      // Separators are normalized to spaces in the HAYSTACK, so a term that
      // still contains one can never line up as a single token. This fails
      // closed (empty result) rather than silently widening the match.
      expect(await titlesMatching("contains_word", "100%")).toEqual([]);
      expect(await titlesMatching("contains_word", "Head_of_Data")).toEqual([]);

      // The tokenized form does match, which is the documented workaround.
      expect(await titlesMatching("contains_word", "O Brien")).toEqual(["O'Brien"]);
      expect(await titlesMatching("contains_word", "Head of Data")).toEqual(["Head_of_Data"]);
    });
  });
});
