/**
 * Integration test for the `process-issues` skill contract.
 *
 * The skill itself is a markdown file invoked by an agent harness, so this
 * test does NOT execute it end-to-end. Instead, it exercises every Neotoma
 * surface the skill is documented to call, in the same order, against
 * mocked operations and the real helpers — catching contract regressions
 * without standing up a live server. End-to-end agent execution is
 * validated manually via `.cursor/skills/process-issues/SKILL.md`.
 *
 * Asserted contract:
 *   - The plan schema is registered and accepts the documented field set.
 *   - A harness `.plan.md` file ingests via `captureHarnessPlan` (combined
 *     entities + file payload + idempotency keys per the skill's recipe).
 *   - When the source issue is private, public-emission redaction throws on
 *     PII leakage so PRs / branch names cannot publish identifiers.
 *   - `submitIssue` enforces the v0.12 reporter-env requirement so the
 *     skill never produces follow-up `add_issue_message` calls without
 *     reporter environment populated.
 */

import { promises as fs } from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { describe, expect, it, vi } from "vitest";

import { captureHarnessPlan } from "../../src/services/plans/capture_harness_plan.js";
import { PLAN_FIELD_SPECS, seedPlanSchema } from "../../src/services/plans/seed_schema.js";
import {
  RedactionGuardError,
  assertPublicEmissionIsClean,
  runRedactionGuard,
} from "../../src/services/issues/redaction_guard.js";
import { IssueValidationError } from "../../src/services/issues/errors.js";

describe("process-issues skill contract", () => {
  it("plan schema covers every field documented in the skill workflow", async () => {
    const fieldNames = new Set(PLAN_FIELD_SPECS.map((s) => s.name));
    // Fields the skill explicitly populates per .cursor/skills/process-issues/SKILL.md step 4.
    for (const required of [
      "title",
      "harness",
      "plan_kind",
      "source_entity_id",
      "source_entity_type",
      "reproduction_environment_kind",
      "git_sha",
      "git_ref",
      "release_tag",
      "app_version",
      "decision_required",
      "decision_blockers",
      "body",
      "public_overview",
      "public_body",
      "data_source",
      "agent_id",
      "status",
      "outcome",
      "worktree_path",
      "branch_name",
      "pr_url",
      "github_issue_url",
    ]) {
      expect(fieldNames.has(required)).toBe(true);
    }

    // seedPlanSchema can be invoked with a mock registry.
    const registry = {
      loadGlobalSchema: vi.fn(async () => null),
      register: vi.fn(async (entry) => entry),
      updateSchemaIncremental: vi.fn(),
    };
    await seedPlanSchema({ registry: registry as unknown as Parameters<typeof seedPlanSchema>[0]["registry"] });
    expect(registry.register).toHaveBeenCalledTimes(1);
  });

  it("captureHarnessPlan produces a payload the skill can hand to /store unchanged", async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), "process-issues-skill-"));
    const file = path.join(dir, "issue-resolution-plan_2d3bdfdc.plan.md");
    await fs.writeFile(
      file,
      `---
name: Issue resolution plan
overview: Auto-generated by process-issues skill
---

# Plan body
`,
      "utf8",
    );
    try {
      const result = await captureHarnessPlan({
        file_path: file,
        harness: "agent",
        source_entity_id: "ent_issue_42",
        source_entity_type: "issue",
        source_message_entity_id: "ent_msg_99",
      });
      expect(result.storePayload.entities).toHaveLength(1);
      const plan = result.storePayload.entities[0] as Record<string, unknown>;
      expect(plan.entity_type).toBe("plan");
      expect(plan.harness).toBe("agent");
      expect(plan.harness_plan_id).toBe("2d3bdfdc");
      expect(plan.source_entity_id).toBe("ent_issue_42");
      expect(result.storePayload.relationships).toEqual([
        {
          relationship_type: "REFERS_TO",
          source_entity_id: "ent_msg_99",
          target_index: 0,
        },
      ]);
      expect(result.storePayload.idempotency_key).toBe(
        "plan-capture-agent-2d3bdfdc",
      );
    } finally {
      await fs.rm(dir, { recursive: true, force: true });
    }
  });

  it("public-emission redaction blocks PII derived from a private issue", () => {
    expect(() =>
      assertPublicEmissionIsClean({
        title: "Fix bug for alice@example.com",
        body: "Reporter alice@example.com hit an error",
        extra_fields: { branch_name: "fix/alice-example-bug" },
      }),
    ).toThrow(RedactionGuardError);

    expect(() =>
      assertPublicEmissionIsClean({
        title: "Fix race condition in compliance reminder",
        body: "Reproduce by running the daemon under load.",
        extra_fields: { branch_name: "fix/compliance-race" },
      }),
    ).not.toThrow();
  });

  it("scan mode returns redacted body for the skill's add_issue_message public-thread post", () => {
    const result = runRedactionGuard({
      title: "",
      body: "Re-tested at /Users/bot/checkout for alice@example.com",
      mode: "scan",
    });
    expect(result.applied).toBe(true);
    expect(result.body).toContain("~/checkout");
    expect(result.body).toMatch(/<EMAIL:[0-9a-f]{4}>/);
    expect(result.body).not.toContain("alice@example.com");
  });

  it("submit_issue contract rejects callers (including the skill's follow-up paths) that omit reporter env", async () => {
    // The skill itself does not call submit_issue, but the underlying
    // contract guarantees follow-up `add_issue_message` calls cannot
    // backfill into a never-submitted issue. Asserting the validation
    // error here keeps the contract stable for the skill's flow.
    const { submitIssue } = await import("../../src/services/issues/issue_operations.js");
    await expect(
      submitIssue(
        {
          // Minimal Operations stub — the validator throws before any of
          // these are touched.
          store: vi.fn(),
        } as unknown as Parameters<typeof submitIssue>[0],
        { title: "x", body: "y", visibility: "public" },
      ),
    ).rejects.toBeInstanceOf(IssueValidationError);
  });
});
