/**
 * TypeScript types for the capability manifest JSON file.
 *
 * This file mirrors the structure of src/shared/capability_manifest.json.
 * The manifest is generated by scripts/generate-capability-manifest.ts —
 * do NOT edit the JSON file by hand.
 */

export interface ToolManifestEntry {
  /** The earliest vX.Y.Z release tag in which this tool appeared. */
  addedInVersion: string;
  /**
   * The first vX.Y.Z release tag in which this tool was NO longer present.
   * Absent for tools that are still active in the current release.
   */
  removedInVersion?: string;
}

export interface CapabilityManifestMeta {
  description: string;
  generated_from: string;
  first_tracked_version: string;
}

export interface CapabilityManifest {
  _meta: CapabilityManifestMeta;
  /** Map of MCP tool name → version metadata. */
  tools: Record<string, ToolManifestEntry>;
}
