/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List existing record types */
        get: operations["listTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieve_records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve records with optional semantic search
         * @description Filter by type and/or match property values. RECOMMENDED: Generate query_embedding client-side from search terms using OpenAI text-embedding-3-small before calling. Server auto-generates if omitted. Use search_mode to control semantic vs keyword matching.
         */
        post: operations["retrieveRecords"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload_file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload file and attach or create record
         * @description Send multipart/form-data with field `file` and optional `record_id`.
         *     If `record_id` is provided, the file is appended to the existing record's `file_urls`.
         *     When `record_id` is omitted, the server analyzes the file (via OpenAI when available) to infer `type` and `properties`,
         *     creates a new record, and associates the uploaded file. Provide an optional `properties` JSON field to bypass analysis
         *     and supply record properties manually. CSV uploads default to creating one record per row (set `csv_row_records=false`
         *     to skip) plus relationships back to the originating dataset record.
         */
        post: operations["uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze_file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze a file without storing it to infer type, summary, and properties */
        post: operations["analyzeFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_file_url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get signed file URL
         * @description Provide a storage path like "files/<record_id>/<filename>".
         */
        get: operations["getFileUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get OpenAPI specification */
        get: operations["getOpenApiSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get server info */
        get: operations["getServerInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/oauth/initiate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initiate MCP OAuth flow */
        post: operations["mcpOAuthInitiate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth authorization endpoint */
        get: operations["mcpOAuthAuthorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OAuth token exchange */
        post: operations["mcpOAuthToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/oauth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get OAuth connection status */
        get: operations["mcpOAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/oauth/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List OAuth connections */
        get: operations["mcpOAuthListConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/oauth/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke OAuth connection */
        delete: operations["mcpOAuthRevokeConnection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query entities */
        post: operations["queryEntities"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get entity by ID */
        get: operations["getEntityById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List observations for entity */
        get: operations["getEntityObservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{id}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List relationships for entity */
        get: operations["getEntityRelationships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge duplicate entities */
        post: operations["mergeEntities"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sources */
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get source by ID */
        get: operations["getSourceById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List observations */
        get: operations["listObservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query observations */
        post: operations["queryObservations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create observation */
        post: operations["createObservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List relationships */
        get: operations["listRelationships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get relationship by ID */
        get: operations["getRelationshipById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List timeline events */
        get: operations["listTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List entity schemas */
        get: operations["listSchemas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schemas/{entity_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get schema by entity type */
        get: operations["getSchemaByEntityType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interpretations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List interpretations */
        get: operations["listInterpretations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard stats */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store structured entities */
        post: operations["storeStructured"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get record by ID */
        get: operations["getRecordById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get record history */
        get: operations["getRecordHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_entity_snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get entity snapshot with provenance */
        post: operations["getEntitySnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/list_observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List observations for entity */
        post: operations["listObservationsForEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_field_provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get field provenance */
        post: operations["getFieldProvenance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create_relationship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create relationship */
        post: operations["createRelationship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/list_relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List relationships */
        post: operations["listRelationshipsForEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/record_comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare records */
        post: operations["recordComparison"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate_embedding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate embedding */
        post: operations["generateEmbedding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RetrieveRecordsRequest: {
            /** @description Filter by record type */
            type?: string;
            /** @description Filter by property values (simple top-level key matching) */
            properties?: {
                [key: string]: unknown;
            };
            /** @description Maximum number of results (default 100, max 500) */
            limit?: number;
            /** @description Search terms for fuzzy/semantic matching (requires query_embedding for semantic mode) */
            search?: string[];
            /**
             * @description Search mode - semantic uses vector embeddings, keyword uses text matching, both combines results
             * @default both
             * @enum {string}
             */
            search_mode: "semantic" | "keyword" | "both";
            /**
             * @description Minimum cosine similarity score for semantic search (0 = no similarity, 1 = identical). Typical scores range 0.3-0.5 for related content.
             * @default 0.3
             */
            similarity_threshold: number;
            /**
             * @description RECOMMENDED: Generate 1536-dimensional embedding client-side using OpenAI text-embedding-3-small from search terms.
             *     - Generate from: search.join with space separator or search array elements combined
             *     - If you generate and include this field, must be non-empty array of exactly 1536 numbers.
             *     - Do NOT send empty array. Omit field entirely if not generating client-side.
             *     - Server will auto-generate if omitted (requires OPENAI_API_KEY on server).
             *     Generation example: Use OpenAI embeddings.create with model text-embedding-3-small and input search.join with space separator
             */
            query_embedding?: number[];
            /** @description When true, response includes a {records,total_count} object instead of a bare array so callers know the full number of matches. */
            include_total_count?: boolean;
        };
        UploadFileRequest: {
            /** @description Existing record ID to attach the file to. Omit to create a new record. */
            record_id?: string;
            /** @description Storage bucket name (optional, defaults to 'files'). */
            bucket?: string;
            /** @description Optional JSON object to use as properties when creating a new record. If provided, automatic analysis is skipped. */
            properties?: string;
            /** @description Optional flag for CSV uploads. Defaults to true. Set to false to skip creating per-row records linked to the dataset. */
            csv_row_records?: boolean;
            /**
             * Format: binary
             * @description File to upload
             */
            file: string;
        };
        FileUrlResponse: {
            /** @description Signed URL for accessing the file */
            url?: string;
        };
        Record: {
            id?: string;
            type?: string;
            /** @description Arbitrary key/value properties stored in JSONB */
            properties?: {
                [key: string]: unknown;
            };
            file_urls?: string[];
            /** @description 1536-dimensional embedding vector (if provided). Note: Embeddings are excluded from responses to reduce payload size. */
            embedding?: number[];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Error: {
            error?: string;
        };
        AnalyzeFileResponse: {
            /** @description Inferred canonical record type */
            type?: string;
            /** @description Structured fields extracted from the file */
            properties?: {
                [key: string]: unknown;
            };
            /** @description Human-readable summary of the file contents */
            summary?: string;
            /** @description Records that were queried during the conversation (if any) */
            records_queried?: components["schemas"]["Record"][];
            /** @description Exact number of records in the final retrieve_records call when available */
            records_total_count?: number;
            /** @description Function calls made during the conversation (if any) */
            function_calls?: {
                name?: string;
                arguments?: {
                    [key: string]: unknown;
                };
            }[];
        };
        ErrorEnvelope: {
            error_code?: string;
            message?: string;
            details?: {
                [key: string]: unknown;
            };
            trace_id?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        Entity: {
            id?: string;
            entity_type?: string;
            canonical_name?: string;
            user_id?: string;
            merged_to_entity_id?: string | null;
            /** Format: date-time */
            merged_at?: string | null;
        };
        EntitySnapshot: {
            entity_id?: string;
            entity_type?: string;
            schema_version?: string;
            snapshot?: {
                [key: string]: unknown;
            };
            raw_fragments?: {
                [key: string]: unknown;
            };
            provenance?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            computed_at?: string;
            observation_count?: number;
            /** Format: date-time */
            last_observation_at?: string;
        };
        Source: {
            id?: string;
            content_hash?: string;
            mime_type?: string;
            storage_url?: string;
            file_size?: number;
            original_filename?: string;
            /** Format: date-time */
            created_at?: string;
            user_id?: string;
        };
        Observation: {
            id?: string;
            entity_id?: string;
            entity_type?: string;
            schema_version?: string;
            source_id?: string | null;
            interpretation_id?: string | null;
            /** Format: date-time */
            observed_at?: string;
            specificity_score?: number;
            source_priority?: number;
            fields?: {
                [key: string]: unknown;
            };
            user_id?: string;
        };
        RelationshipSnapshot: {
            relationship_key?: string;
            relationship_type?: string;
            source_entity_id?: string;
            target_entity_id?: string;
            schema_version?: string;
            snapshot?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            computed_at?: string;
            observation_count?: number;
            /** Format: date-time */
            last_observation_at?: string;
            provenance?: {
                [key: string]: unknown;
            };
            user_id?: string;
        };
        TimelineEvent: {
            id?: string;
            event_type?: string;
            /** Format: date-time */
            event_timestamp?: string;
            source_id?: string;
            entity_ids?: string[];
            properties?: {
                [key: string]: unknown;
            };
        };
        EntitySchema: {
            entity_type?: string;
            schema_version?: string;
            field_names?: string[];
            field_summary?: {
                [key: string]: unknown;
            };
        };
        Interpretation: {
            id?: string;
            source_id?: string;
            status?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            completed_at?: string;
        };
        Stats: {
            entities?: number;
            sources?: number;
            observations?: number;
            relationships?: number;
            timeline_events?: number;
        };
        StoreStructuredRequest: {
            entities?: {
                [key: string]: unknown;
            }[];
            source_priority?: number;
            user_id?: string;
        };
        StoreStructuredResponse: {
            success?: boolean;
            entities?: {
                entity_id?: string;
                entity_type?: string;
                observation_id?: string;
            }[];
        };
        OAuthInitiateRequest: {
            connection_id: string;
            client_name?: string;
        };
        OAuthInitiateResponse: {
            auth_url?: string;
            connection_id?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        OAuthStatusResponse: {
            status?: string;
            connection_id?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Distinct record types */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        types?: string[];
                    };
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    retrieveRecords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrieveRecordsRequest"];
            };
        };
        responses: {
            /** @description Records (optionally with total_count metadata) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record"][] | {
                        records?: components["schemas"]["Record"][];
                        /** @description Exact number of matching records */
                        total_count?: number;
                    };
                };
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UploadFileRequest"];
            };
        };
        responses: {
            /** @description Updated record after attaching the file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record"];
                };
            };
            /** @description Newly created record derived from uploaded file */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record"];
                };
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    analyzeFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description File to analyze
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Analysis result describing the inferred record type and metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeFileResponse"];
                };
            };
            /** @description Missing file or invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Record not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Analysis service failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFileUrl: {
        parameters: {
            query: {
                file_path: string;
                expires_in?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUrlResponse"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
        };
    };
    getOpenApiSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI specification in YAML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    getServerInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    mcpOAuthInitiate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthInitiateRequest"];
            };
        };
        responses: {
            /** @description OAuth initiation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthInitiateResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    mcpOAuthAuthorize: {
        parameters: {
            query: {
                redirect_uri: string;
                state: string;
                code_challenge: string;
                code_challenge_method: string;
                client_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to authorization URL */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mcpOAuthToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    grant_type?: string;
                    code?: string;
                };
            };
        };
        responses: {
            /** @description OAuth token response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token?: string;
                        token_type?: string;
                        expires_in?: number;
                    };
                };
            };
            /** @description Token exchange error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    mcpOAuthStatus: {
        parameters: {
            query: {
                connection_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStatusResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    mcpOAuthListConnections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        connections?: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    mcpOAuthRevokeConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
        };
    };
    queryEntities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_type?: string;
                    search?: string;
                    limit?: number;
                    offset?: number;
                    include_merged?: boolean;
                    user_id?: string;
                };
            };
        };
        responses: {
            /** @description Entity list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entities?: components["schemas"]["EntitySnapshot"][];
                        total?: number;
                        limit?: number;
                        offset?: number;
                    };
                };
            };
        };
    };
    getEntityById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySnapshot"];
                };
            };
            /** @description Entity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEntityObservations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        observations?: components["schemas"]["Observation"][];
                    };
                };
            };
        };
    };
    getEntityRelationships: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relationships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        relationships?: components["schemas"]["RelationshipSnapshot"][];
                    };
                };
            };
        };
    };
    mergeEntities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    from_entity_id?: string;
                    to_entity_id?: string;
                    merge_reason?: string;
                    user_id?: string;
                };
            };
        };
        responses: {
            /** @description Merge result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        observations_moved?: number;
                        /** Format: date-time */
                        merged_at?: string;
                    };
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: {
                user_id?: string;
                search?: string;
                mime_type?: string;
                source_type?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sources?: components["schemas"]["Source"][];
                    };
                };
            };
        };
    };
    getSourceById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
        };
    };
    listObservations: {
        parameters: {
            query?: {
                user_id?: string;
                source_id?: string;
                entity_id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        observations?: components["schemas"]["Observation"][];
                    };
                };
            };
        };
    };
    queryObservations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_id?: string;
                    entity_type?: string;
                    limit?: number;
                    offset?: number;
                    user_id?: string;
                };
            };
        };
        responses: {
            /** @description Observations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        observations?: components["schemas"]["Observation"][];
                        total?: number;
                        limit?: number;
                        offset?: number;
                    };
                };
            };
        };
    };
    createObservation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Observation created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listRelationships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relationships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        relationships?: components["schemas"]["RelationshipSnapshot"][];
                    };
                };
            };
        };
    };
    getRelationshipById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relationship */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipSnapshot"];
                };
            };
        };
    };
    listTimeline: {
        parameters: {
            query?: {
                start_date?: string;
                end_date?: string;
                event_type?: string;
                user_id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events?: components["schemas"]["TimelineEvent"][];
                    };
                };
            };
        };
    };
    listSchemas: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schemas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        schemas?: components["schemas"]["EntitySchema"][];
                    };
                };
            };
        };
    };
    getSchemaByEntityType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySchema"];
                };
            };
        };
    };
    listInterpretations: {
        parameters: {
            query?: {
                user_id?: string;
                source_id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Interpretations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        interpretations?: components["schemas"]["Interpretation"][];
                    };
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    storeStructured: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreStructuredRequest"];
            };
        };
        responses: {
            /** @description Store result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreStructuredResponse"];
                };
            };
        };
    };
    getRecordById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record"];
                };
            };
        };
    };
    getRecordHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Record history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getEntitySnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_id?: string;
                };
            };
        };
        responses: {
            /** @description Entity snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySnapshot"];
                };
            };
        };
    };
    listObservationsForEntity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_id?: string;
                    limit?: number;
                    offset?: number;
                };
            };
        };
        responses: {
            /** @description Observations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        observations?: components["schemas"]["Observation"][];
                    };
                };
            };
        };
    };
    getFieldProvenance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_id?: string;
                    field?: string;
                };
            };
        };
        responses: {
            /** @description Provenance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Relationship created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipSnapshot"];
                };
            };
        };
    };
    listRelationshipsForEntity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Relationships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        relationships?: components["schemas"]["RelationshipSnapshot"][];
                    };
                };
            };
        };
    };
    recordComparison: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Comparison result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    generateEmbedding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Embedding result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
