/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/get_file_url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get signed file URL
         * @description Provide a storage path like "files/<source_id>/<filename>".
         */
        get: operations["getFileUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get OpenAPI specification */
        get: operations["getOpenApiSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get server info */
        get: operations["getServerInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/oauth/initiate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initiate MCP OAuth flow */
        post: operations["mcpOAuthInitiate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth authorization endpoint */
        get: operations["mcpOAuthAuthorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OAuth token exchange */
        post: operations["mcpOAuthToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/oauth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get OAuth connection status */
        get: operations["mcpOAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/oauth/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List OAuth connections */
        get: operations["mcpOAuthListConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/oauth/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke OAuth connection */
        delete: operations["mcpOAuthRevokeConnection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query entities */
        post: operations["queryEntities"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get entity by ID */
        get: operations["getEntityById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List observations for entity */
        get: operations["getEntityObservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{id}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List relationships for entity */
        get: operations["getEntityRelationships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge duplicate entities */
        post: operations["mergeEntities"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sources */
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get source by ID */
        get: operations["getSourceById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List observations */
        get: operations["listObservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query observations */
        post: operations["queryObservations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create observation */
        post: operations["createObservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships": {
        parameters: {
            query?: {
                source_entity_id?: string;
                target_entity_id?: string;
                relationship_type?: string;
                direction?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List relationships */
        get: operations["listRelationships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get relationship by ID */
        get: operations["getRelationshipById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get relationship snapshot with provenance */
        post: operations["getRelationshipSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List timeline events */
        get: operations["listTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schemas": {
        parameters: {
            query?: {
                user_id?: string;
                entity_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List entity schemas */
        get: operations["listSchemas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schemas/{entity_type}": {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get schema by entity type */
        get: operations["getSchemaByEntityType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interpretations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List interpretations */
        get: operations["listInterpretations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard stats */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store structured entities */
        post: operations["storeStructured"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store/unstructured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store unstructured file (raw upload with optional AI interpretation) */
        post: operations["storeUnstructured"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_entity_snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get entity snapshot with provenance */
        post: operations["getEntitySnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/list_observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List observations for entity */
        post: operations["listObservationsForEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_field_provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get field provenance */
        post: operations["getFieldProvenance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create_relationship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create relationship */
        post: operations["createRelationship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/list_relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List relationships */
        post: operations["listRelationshipsForEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieve_entity_by_identifier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve entity by identifier
         * @description Search for entity by name, email, or other identifier
         */
        post: operations["retrieveEntityByIdentifier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieve_related_entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve related entities
         * @description Get entities connected via relationships with n-hop traversal support
         */
        post: operations["retrieveRelatedEntities"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieve_graph_neighborhood": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve graph neighborhood
         * @description Get complete graph neighborhood including entities, relationships, sources, and events
         */
        post: operations["retrieveGraphNeighborhood"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delete_entity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete entity
         * @description Soft delete entity (creates deletion observation, reversible)
         */
        post: operations["deleteEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restore_entity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore entity
         * @description Restore a soft-deleted entity
         */
        post: operations["restoreEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delete_relationship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete relationship
         * @description Soft delete relationship (creates deletion observation, reversible)
         */
        post: operations["deleteRelationship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restore_relationship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore relationship
         * @description Restore a soft-deleted relationship
         */
        post: operations["restoreRelationship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze_schema_candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze schema candidates
         * @description Analyze raw_fragments to identify fields for schema promotion
         */
        post: operations["analyzeSchemaCandidates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_schema_recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get schema recommendations
         * @description Get schema update recommendations from raw_fragments analysis
         */
        post: operations["getSchemaRecommendations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update_schema_incremental": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update schema incrementally
         * @description Add new fields to existing schema
         */
        post: operations["updateSchemaIncremental"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register_schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register schema
         * @description Register a new schema or schema version
         */
        post: operations["registerSchema"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reinterpret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reinterpret source
         * @description Re-run AI interpretation on existing source
         */
        post: operations["reinterpret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create correction
         * @description Create high-priority correction observation
         */
        post: operations["correct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_authenticated_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get authenticated user
         * @description Get authenticated user ID for current session
         */
        post: operations["getAuthenticatedUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health_check_snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Health check snapshots
         * @description Check for stale entity snapshots
         */
        post: operations["healthCheckSnapshots"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FileUrlResponse: {
            /** @description Signed URL for accessing the file */
            url?: string;
        };
        Error: {
            error?: string;
        };
        ErrorEnvelope: {
            error_code?: string;
            message?: string;
            details?: {
                [key: string]: unknown;
            };
            trace_id?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        Entity: {
            id?: string;
            entity_type?: string;
            canonical_name?: string;
            user_id?: string;
            merged_to_entity_id?: string | null;
            /** Format: date-time */
            merged_at?: string | null;
        };
        EntitySnapshot: {
            entity_id?: string;
            entity_type?: string;
            schema_version?: string;
            snapshot?: {
                [key: string]: unknown;
            };
            raw_fragments?: {
                [key: string]: unknown;
            };
            provenance?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            computed_at?: string;
            observation_count?: number;
            /** Format: date-time */
            last_observation_at?: string;
        };
        Source: {
            id?: string;
            content_hash?: string;
            mime_type?: string;
            storage_url?: string;
            file_size?: number;
            original_filename?: string;
            /** Format: date-time */
            created_at?: string;
            user_id?: string;
        };
        Observation: {
            id?: string;
            entity_id?: string;
            entity_type?: string;
            schema_version?: string;
            source_id?: string | null;
            interpretation_id?: string | null;
            /** Format: date-time */
            observed_at?: string;
            specificity_score?: number;
            source_priority?: number;
            fields?: {
                [key: string]: unknown;
            };
            user_id?: string;
        };
        RelationshipSnapshot: {
            relationship_key?: string;
            relationship_type?: string;
            source_entity_id?: string;
            target_entity_id?: string;
            schema_version?: string;
            snapshot?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            computed_at?: string;
            observation_count?: number;
            /** Format: date-time */
            last_observation_at?: string;
            provenance?: {
                [key: string]: unknown;
            };
            user_id?: string;
        };
        TimelineEvent: {
            id?: string;
            event_type?: string;
            /** Format: date-time */
            event_timestamp?: string;
            source_id?: string;
            entity_ids?: string[];
            properties?: {
                [key: string]: unknown;
            };
        };
        EntitySchema: {
            entity_type?: string;
            schema_version?: string;
            field_names?: string[];
            field_summary?: {
                [key: string]: unknown;
            };
        };
        Interpretation: {
            id?: string;
            source_id?: string;
            status?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            completed_at?: string;
        };
        Stats: {
            entities?: number;
            sources?: number;
            observations?: number;
            relationships?: number;
            timeline_events?: number;
        };
        StoreStructuredRequest: {
            entities: {
                [key: string]: unknown;
            }[];
            /**
             * @description Optional. Create relationships between entities in this request. Indices refer to the entities array (0-based).
             *     Enables one-call chat persistence: store [conversation, agent_message] with relationships [{ relationship_type: "PART_OF", source_index: 1, target_index: 0 }].
             */
            relationships?: {
                /** @enum {string} */
                relationship_type: "PART_OF" | "CORRECTS" | "REFERS_TO" | "SETTLES" | "DUPLICATE_OF" | "DEPENDS_ON" | "SUPERSEDES" | "EMBEDS";
                /** @description Index into the entities array for the source entity */
                source_index: number;
                /** @description Index into the entities array for the target entity */
                target_index: number;
            }[];
            source_priority?: number;
            idempotency_key: string;
            user_id?: string;
            /**
             * @description Optional. For agent-provided structured data, omit so the source has no filename (null).
             *     Pass only when mirroring a real file name or when a display label is desired.
             */
            original_filename?: string;
        };
        StoreStructuredResponse: {
            success?: boolean;
            entities?: {
                entity_id?: string;
                entity_type?: string;
                observation_id?: string;
            }[];
        };
        StoreUnstructuredRequest: {
            /** @description Base64-encoded file content */
            file_content: string;
            /** @description MIME type of the file */
            mime_type: string;
            /** @description Optional idempotency key; if omitted, content hash is used */
            idempotency_key?: string;
            original_filename?: string;
            /**
             * @description Run AI interpretation after store
             * @default true
             */
            interpret: boolean;
            /** Format: uuid */
            user_id?: string;
        };
        StoreUnstructuredResponse: {
            source_id?: string;
            content_hash?: string;
            file_size?: number;
            deduplicated?: boolean;
            interpretation?: {
                [key: string]: unknown;
            };
            entity_ids?: string[];
        };
        GetRelationshipSnapshotRequest: {
            /** @enum {string} */
            relationship_type: "PART_OF" | "CORRECTS" | "REFERS_TO" | "SETTLES" | "DUPLICATE_OF" | "DEPENDS_ON" | "SUPERSEDES" | "EMBEDS";
            source_entity_id: string;
            target_entity_id: string;
        };
        GetRelationshipSnapshotResponse: {
            snapshot: components["schemas"]["RelationshipSnapshot"];
            observations: {
                id?: string;
                source_id?: string;
                observed_at?: string;
                specificity_score?: number;
                source_priority?: number;
                metadata?: Record<string, never>;
            }[];
        };
        OAuthInitiateRequest: {
            connection_id: string;
            client_name?: string;
            redirect_uri?: string;
        };
        OAuthInitiateResponse: {
            auth_url?: string;
            connection_id?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        OAuthStatusResponse: {
            status?: string;
            connection_id?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getFileUrl: {
        parameters: {
            query: {
                file_path: string;
                expires_in?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUrlResponse"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
        };
    };
    getOpenApiSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI specification in YAML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    getServerInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    mcpOAuthInitiate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthInitiateRequest"];
            };
        };
        responses: {
            /** @description OAuth initiation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthInitiateResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    mcpOAuthAuthorize: {
        parameters: {
            query: {
                redirect_uri: string;
                state: string;
                code_challenge: string;
                code_challenge_method: string;
                client_id?: string;
                dev_stub?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to authorization URL */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mcpOAuthToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    grant_type?: string;
                    code?: string;
                };
            };
        };
        responses: {
            /** @description OAuth token response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token?: string;
                        token_type?: string;
                        expires_in?: number;
                    };
                };
            };
            /** @description Token exchange error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user_id?: string;
                        email?: string;
                    };
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    mcpOAuthStatus: {
        parameters: {
            query: {
                connection_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStatusResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    mcpOAuthListConnections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        connections?: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    mcpOAuthRevokeConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
        };
    };
    queryEntities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_type?: string;
                    search?: string;
                    limit?: number;
                    offset?: number;
                    include_merged?: boolean;
                    user_id?: string;
                };
            };
        };
        responses: {
            /** @description Entity list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entities?: components["schemas"]["EntitySnapshot"][];
                        total?: number;
                        limit?: number;
                        offset?: number;
                    };
                };
            };
        };
    };
    getEntityById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySnapshot"];
                };
            };
            /** @description Entity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEntityObservations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        observations?: components["schemas"]["Observation"][];
                    };
                };
            };
        };
    };
    getEntityRelationships: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relationships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        relationships?: components["schemas"]["RelationshipSnapshot"][];
                    };
                };
            };
        };
    };
    mergeEntities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    from_entity_id?: string;
                    to_entity_id?: string;
                    merge_reason?: string;
                    user_id?: string;
                };
            };
        };
        responses: {
            /** @description Merge result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        observations_moved?: number;
                        /** Format: date-time */
                        merged_at?: string;
                    };
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: {
                user_id?: string;
                search?: string;
                mime_type?: string;
                source_type?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sources?: components["schemas"]["Source"][];
                    };
                };
            };
        };
    };
    getSourceById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
        };
    };
    listObservations: {
        parameters: {
            query?: {
                user_id?: string;
                source_id?: string;
                entity_id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        observations?: components["schemas"]["Observation"][];
                    };
                };
            };
        };
    };
    queryObservations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_id?: string;
                    entity_type?: string;
                    limit?: number;
                    offset?: number;
                    user_id?: string;
                };
            };
        };
        responses: {
            /** @description Observations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        observations?: components["schemas"]["Observation"][];
                        total?: number;
                        limit?: number;
                        offset?: number;
                    };
                };
            };
        };
    };
    createObservation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Observation created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listRelationships: {
        parameters: {
            query?: {
                source_entity_id?: string;
                target_entity_id?: string;
                relationship_type?: string;
                direction?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relationships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        relationships?: components["schemas"]["RelationshipSnapshot"][];
                    };
                };
            };
        };
    };
    getRelationshipById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relationship */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipSnapshot"];
                };
            };
        };
    };
    getRelationshipSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetRelationshipSnapshotRequest"];
            };
        };
        responses: {
            /** @description Relationship snapshot and observations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRelationshipSnapshotResponse"];
                };
            };
        };
    };
    listTimeline: {
        parameters: {
            query?: {
                start_date?: string;
                end_date?: string;
                event_type?: string;
                user_id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events?: components["schemas"]["TimelineEvent"][];
                    };
                };
            };
        };
    };
    listSchemas: {
        parameters: {
            query?: {
                user_id?: string;
                entity_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schemas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        schemas?: components["schemas"]["EntitySchema"][];
                    };
                };
            };
        };
    };
    getSchemaByEntityType: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: never;
            path: {
                entity_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySchema"];
                };
            };
        };
    };
    listInterpretations: {
        parameters: {
            query?: {
                user_id?: string;
                source_id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Interpretations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        interpretations?: components["schemas"]["Interpretation"][];
                    };
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: {
                user_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    storeStructured: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreStructuredRequest"];
            };
        };
        responses: {
            /** @description Store result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreStructuredResponse"];
                };
            };
        };
    };
    storeUnstructured: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreUnstructuredRequest"];
            };
        };
        responses: {
            /** @description Store result with source_id and optional interpretation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreUnstructuredResponse"];
                };
            };
        };
    };
    getEntitySnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_id?: string;
                };
            };
        };
        responses: {
            /** @description Entity snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySnapshot"];
                };
            };
        };
    };
    listObservationsForEntity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_id?: string;
                    limit?: number;
                    offset?: number;
                };
            };
        };
        responses: {
            /** @description Observations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        observations?: components["schemas"]["Observation"][];
                    };
                };
            };
        };
    };
    getFieldProvenance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_id?: string;
                    field?: string;
                };
            };
        };
        responses: {
            /** @description Provenance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Relationship created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipSnapshot"];
                };
            };
        };
    };
    listRelationshipsForEntity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Relationships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        relationships?: components["schemas"]["RelationshipSnapshot"][];
                    };
                };
            };
        };
    };
    retrieveEntityByIdentifier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Identifier to search for (name, email, etc.) */
                    identifier: string;
                    /** @description Optional entity type to limit search */
                    entity_type?: string;
                };
            };
        };
        responses: {
            /** @description Entity search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entities?: components["schemas"]["Entity"][];
                        total?: number;
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    retrieveRelatedEntities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_id: string;
                    relationship_types?: string[];
                    /**
                     * @default both
                     * @enum {string}
                     */
                    direction?: "inbound" | "outbound" | "both";
                    /** @default 1 */
                    max_hops?: number;
                    /** @default true */
                    include_entities?: boolean;
                };
            };
        };
        responses: {
            /** @description Related entities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    retrieveGraphNeighborhood: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    node_id: string;
                    /**
                     * @default entity
                     * @enum {string}
                     */
                    node_type?: "entity" | "source";
                    /** @default true */
                    include_relationships?: boolean;
                    /** @default true */
                    include_sources?: boolean;
                    /** @default true */
                    include_events?: boolean;
                    /** @default false */
                    include_observations?: boolean;
                };
            };
        };
        responses: {
            /** @description Graph neighborhood */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deleteEntity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_id: string;
                    entity_type: string;
                    reason?: string;
                    user_id?: string;
                };
            };
        };
        responses: {
            /** @description Entity deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    restoreEntity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_id: string;
                    entity_type: string;
                    reason?: string;
                    user_id?: string;
                };
            };
        };
        responses: {
            /** @description Entity restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deleteRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    relationship_type: "PART_OF" | "CORRECTS" | "REFERS_TO" | "SETTLES" | "DUPLICATE_OF" | "DEPENDS_ON" | "SUPERSEDES" | "EMBEDS";
                    source_entity_id: string;
                    target_entity_id: string;
                    reason?: string;
                    user_id?: string;
                };
            };
        };
        responses: {
            /** @description Relationship deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    restoreRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    relationship_type: "PART_OF" | "CORRECTS" | "REFERS_TO" | "SETTLES" | "DUPLICATE_OF" | "DEPENDS_ON" | "SUPERSEDES" | "EMBEDS";
                    source_entity_id: string;
                    target_entity_id: string;
                    reason?: string;
                    user_id?: string;
                };
            };
        };
        responses: {
            /** @description Relationship restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    analyzeSchemaCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    entity_type?: string;
                    user_id?: string;
                    /** @default 5 */
                    min_frequency?: number;
                    /** @default 0.8 */
                    min_confidence?: number;
                };
            };
        };
        responses: {
            /** @description Schema candidates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getSchemaRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_type: string;
                    user_id?: string;
                    /** @enum {string} */
                    source?: "raw_fragments" | "agent" | "inference" | "all";
                    /** @enum {string} */
                    status?: "pending" | "approved" | "rejected";
                };
            };
        };
        responses: {
            /** @description Schema recommendations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    updateSchemaIncremental: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_type: string;
                    fields_to_add: {
                        field_name: string;
                        /** @enum {string} */
                        field_type: "string" | "number" | "date" | "boolean" | "array" | "object";
                        /** @default false */
                        required?: boolean;
                        /** @enum {string} */
                        reducer_strategy?: "last_write" | "highest_priority" | "most_specific" | "merge_array";
                    }[];
                    schema_version?: string;
                    /** @default false */
                    user_specific?: boolean;
                    user_id?: string;
                    /** @default true */
                    activate?: boolean;
                    /** @default false */
                    migrate_existing?: boolean;
                };
            };
        };
        responses: {
            /** @description Schema updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    registerSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_type: string;
                    schema_definition: {
                        [key: string]: unknown;
                    };
                    reducer_config: {
                        [key: string]: unknown;
                    };
                    /** @default 1.0 */
                    schema_version?: string;
                    /** @default false */
                    user_specific?: boolean;
                    user_id?: string;
                    /** @default false */
                    activate?: boolean;
                };
            };
        };
        responses: {
            /** @description Schema registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    reinterpret: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    source_id: string;
                    interpretation_config?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Source reinterpreted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    correct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    entity_id: string;
                    entity_type: string;
                    field: string;
                    value: unknown;
                    idempotency_key: string;
                    user_id?: string;
                };
            };
        };
        responses: {
            /** @description Correction created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getAuthenticatedUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description User ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user_id?: string;
                    };
                };
            };
        };
    };
    healthCheckSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default false */
                    auto_fix?: boolean;
                };
            };
        };
        responses: {
            /** @description Health check results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
