/**
 * Minimal, non-secret `.env.development` for a git worktree.
 *
 * Worktree setup writes this file from an explicit ALLOWLIST of non-secret
 * keys. It never copies an existing env file and never reads anything outside
 * the repository: values come from the safe defaults below (which are kept
 * equal to the committed `.env.example` by a test), not from the operator's
 * home directory or from another checkout.
 *
 * A developer who wants credentials in a worktree sets them deliberately
 * (shell environment, or their own gitignored `.env` in the worktree).
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/** Key names that must never appear in a generated worktree env file. */
export const CREDENTIAL_KEY_PATTERN =
  /(TOKEN|SECRET|KEY|MNEMONIC|PASSWORD|PASSWD|PAT|PRIVATE|CREDENTIAL)/i;

/** Port and URL defaults. Kept equal to `.env.example` (see the test suite). */
export const DEFAULT_PORT = '3000';
export const DEFAULT_HTTP_PORT = '3080';
export const DEFAULT_WS_PORT = '8280';

/**
 * The ONLY keys worktree setup may write. Each entry is a non-credential
 * setting that local development needs to boot, with a safe default.
 */
export const WORKTREE_DEV_ENV_ALLOWLIST = Object.freeze([
  { key: 'NEOTOMA_ENV', value: () => 'development' },
  // Branch-local data directory, so a worktree never shares another checkout's data.
  { key: 'NEOTOMA_DATA_DIR', value: (repoRoot) => join(repoRoot, 'data') },
  { key: 'PORT', value: () => DEFAULT_PORT },
  { key: 'HTTP_PORT', value: () => DEFAULT_HTTP_PORT },
  { key: 'WS_PORT', value: () => DEFAULT_WS_PORT },
  { key: 'VITE_API_BASE_URL', value: () => `http://localhost:${DEFAULT_HTTP_PORT}` },
]);

function assertAllowlistIsNonSecret() {
  for (const { key } of WORKTREE_DEV_ENV_ALLOWLIST) {
    if (CREDENTIAL_KEY_PATTERN.test(key)) {
      throw new Error(`worktree dev env allowlist contains a credential-named key: ${key}`);
    }
  }
}

function formatValue(value) {
  return /^[A-Za-z0-9_./:@+-]+$/.test(value) ? value : JSON.stringify(value);
}

/** Render the dev env file contents for the repository rooted at `repoRoot`. */
export function buildWorktreeDevEnv(repoRoot) {
  assertAllowlistIsNonSecret();
  const lines = [
    '# Generated by scripts/write-worktree-dev-env.js: non-secret local-dev settings only.',
    '# No credentials are written here. To use credentials in this worktree, set them',
    '# yourself (shell environment, or your own gitignored `.env` in this directory).',
  ];
  for (const { key, value } of WORKTREE_DEV_ENV_ALLOWLIST) {
    lines.push(`${key}=${formatValue(value(repoRoot))}`);
  }
  return `${lines.join('\n')}\n`;
}

/**
 * The repository root is the given directory, and only if it is the Neotoma
 * package. Reads `package.json` inside that directory and nothing else.
 */
export function isNeotomaRepoRoot(dir) {
  const manifest = join(dir, 'package.json');
  if (!existsSync(manifest)) return false;
  try {
    return JSON.parse(readFileSync(manifest, 'utf-8')).name === 'neotoma';
  } catch {
    return false;
  }
}

/** Count (never print) credential-named keys already present in a file inside the repo. */
function countCredentialNamedKeys(file) {
  let count = 0;
  for (const line of readFileSync(file, 'utf-8').split('\n')) {
    const match = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/.exec(line);
    if (match && CREDENTIAL_KEY_PATTERN.test(match[1])) count += 1;
  }
  return count;
}

/**
 * Write `.env.development` in `repoRoot`. An existing file is left alone unless
 * `force` is set, so a developer's own settings are never clobbered.
 */
export function writeWorktreeDevEnv(repoRoot, { force = false } = {}) {
  const destination = join(repoRoot, '.env.development');
  if (existsSync(destination) && !force) {
    return {
      status: 'kept',
      destination,
      credentialNamedKeys: countCredentialNamedKeys(destination),
    };
  }
  writeFileSync(destination, buildWorktreeDevEnv(repoRoot), { encoding: 'utf-8' });
  return { status: 'written', destination, credentialNamedKeys: 0 };
}
