/**
 * Minimal, non-secret `.env.development` for a git worktree.
 *
 * Worktree setup writes this file from an explicit ALLOWLIST of non-secret
 * keys. It never copies an existing env file and never reads anything outside
 * the repository: values come from the safe defaults below (which are kept
 * equal to the committed `.env.example` by a test), not from the operator's
 * home directory or from another checkout.
 *
 * A developer who wants credentials in a worktree sets them deliberately
 * (shell environment, or their own gitignored `.env` in the worktree).
 */

import { randomBytes } from 'node:crypto';
import {
  closeSync,
  constants,
  existsSync,
  lstatSync,
  openSync,
  readFileSync,
  renameSync,
  unlinkSync,
  writeSync,
} from 'node:fs';
import path, { join } from 'node:path';

/** Key names that must never appear in a generated worktree env file. */
export const CREDENTIAL_KEY_PATTERN =
  /(TOKEN|SECRET|KEY|MNEMONIC|PASSWORD|PASSWD|PAT|PRIVATE|CREDENTIAL)/i;

/** Port and URL defaults. Kept equal to `.env.example` (see the test suite). */
export const DEFAULT_PORT = '3000';
export const DEFAULT_HTTP_PORT = '3080';
export const DEFAULT_WS_PORT = '8280';

/**
 * Portable form of a filesystem path for a generated env file. Where the path
 * flavour uses backslash as its separator (Windows), the separators become
 * forward slashes, which Node accepts on Windows and which mean the same thing
 * to every consumer of the file. This is the ONLY place a backslash is
 * converted: on other platforms a backslash is an ordinary character of a
 * directory name and is still rejected by the value check.
 */
export function portablePath(value, pathApi = path) {
  return pathApi.sep === '\\' ? value.replace(/\\/g, '/') : value;
}

/**
 * The ONLY keys worktree setup may write. Each entry is a non-credential
 * setting that local development needs to boot, with a safe default.
 */
export const WORKTREE_DEV_ENV_ALLOWLIST = Object.freeze([
  { key: 'NEOTOMA_ENV', value: () => 'development' },
  // Branch-local data directory, so a worktree never shares another checkout's data.
  {
    key: 'NEOTOMA_DATA_DIR',
    value: (repoRoot, pathApi) => portablePath(pathApi.join(repoRoot, 'data'), pathApi),
  },
  { key: 'PORT', value: () => DEFAULT_PORT },
  { key: 'HTTP_PORT', value: () => DEFAULT_HTTP_PORT },
  { key: 'WS_PORT', value: () => DEFAULT_WS_PORT },
  { key: 'VITE_API_BASE_URL', value: () => `http://localhost:${DEFAULT_HTTP_PORT}` },
]);

function assertAllowlistIsNonSecret() {
  for (const { key } of WORKTREE_DEV_ENV_ALLOWLIST) {
    if (CREDENTIAL_KEY_PATTERN.test(key)) {
      throw new Error(`worktree dev env allowlist contains a credential-named key: ${key}`);
    }
  }
}

/** Characters a generated value may contain. Anything else is rejected, never escaped. */
const SAFE_VALUE_CHARS = /^[A-Za-z0-9_./:@+ -]*$/u;
const BARE_VALUE = /^[A-Za-z0-9_./:@+-]+$/;

/**
 * Generated files are read by both dotenv parsers and shell launchers, so a
 * value is only written when it is made of characters that mean the same thing
 * to all of them. Rejected values are not echoed.
 */
function formatValue(key, value) {
  if (!SAFE_VALUE_CHARS.test(value)) {
    throw new Error(
      `cannot write ${key}: the value contains characters that are not allowed in a generated ` +
        'env file (allowed: letters, digits, space and _ . / : @ + -). ' +
        'Move the checkout to a path made of those characters, or set the value yourself.'
    );
  }
  return BARE_VALUE.test(value) ? value : JSON.stringify(value);
}

/**
 * Render the dev env file contents for the repository rooted at `repoRoot`.
 * `pathApi` selects the path flavour (defaults to the running platform's).
 */
export function buildWorktreeDevEnv(repoRoot, { pathApi = path } = {}) {
  assertAllowlistIsNonSecret();
  const lines = [
    '# Generated by scripts/write-worktree-dev-env.js: non-secret local-dev settings only.',
    '# No credentials are written here. To use credentials in this worktree, set them',
    '# yourself (shell environment, or your own gitignored `.env` in this directory).',
  ];
  for (const { key, value } of WORKTREE_DEV_ENV_ALLOWLIST) {
    lines.push(`${key}=${formatValue(key, value(repoRoot, pathApi))}`);
  }
  return `${lines.join('\n')}\n`;
}

/**
 * The repository root is the given directory, and only if it is the Neotoma
 * package. Reads `package.json` inside that directory and nothing else.
 */
export function isNeotomaRepoRoot(dir) {
  const manifest = join(dir, 'package.json');
  if (!existsSync(manifest)) return false;
  try {
    return JSON.parse(readFileSync(manifest, 'utf-8')).name === 'neotoma';
  } catch {
    return false;
  }
}

/**
 * Inspect the destination directory entry WITHOUT following links or opening
 * it. Returns null when nothing is there, otherwise 'file' or 'symlink'.
 * Anything else (directory, device, socket, ...) is refused.
 */
function inspectDestination(destination) {
  let stat;
  try {
    stat = lstatSync(destination);
  } catch (error) {
    if (error && error.code === 'ENOENT') return null;
    throw error;
  }
  if (stat.isSymbolicLink()) return 'symlink';
  if (stat.isFile()) return 'file';
  throw new Error(`${destination} exists and is not a regular file; leaving it alone.`);
}

/**
 * Create `path` exclusively (never follows a link, never truncates) and write
 * `contents` to it. Returns false when something already occupies the path.
 */
function createExclusive(path, contents) {
  const flags =
    constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | (constants.O_NOFOLLOW || 0);
  let fd;
  try {
    fd = openSync(path, flags, 0o600);
  } catch (error) {
    if (error && error.code === 'EEXIST') return false;
    throw error;
  }
  try {
    writeSync(fd, contents);
  } finally {
    closeSync(fd);
  }
  return true;
}

/**
 * Replace the destination directory entry atomically. The new content goes to
 * a fresh exclusive temp file beside it, then is renamed over the entry, so a
 * symlink or hard link at the destination is replaced, never written through.
 */
function replaceDestination(repoRoot, destination, contents) {
  const temp = join(repoRoot, `.env.development.${randomBytes(6).toString('hex')}.tmp`);
  if (!createExclusive(temp, contents)) {
    throw new Error('could not create a temporary file for regeneration');
  }
  try {
    renameSync(temp, destination);
  } catch (error) {
    try {
      unlinkSync(temp);
    } catch {
      // The temp file is already gone; nothing more to clean up.
    }
    throw error;
  }
}

/**
 * Write `.env.development` in `repoRoot`. An existing entry is left alone (and
 * never opened or read) unless `force` is set; regeneration replaces the
 * directory entry itself and never writes through a link.
 */
export function writeWorktreeDevEnv(repoRoot, { force = false } = {}) {
  const destination = join(repoRoot, '.env.development');
  const existing = inspectDestination(destination);
  if (existing && !force) {
    return { status: 'kept', destination };
  }
  const contents = buildWorktreeDevEnv(repoRoot);
  if (existing) {
    replaceDestination(repoRoot, destination, contents);
    return { status: 'written', destination };
  }
  if (!createExclusive(destination, contents)) {
    return { status: 'kept', destination };
  }
  return { status: 'written', destination };
}
