#!/bin/bash
# Helper script to get MCP authentication (session token - deprecated)
# Usage: ./scripts/get_mcp_token.sh

set -euo pipefail

echo "⚠️  DEPRECATED: Session tokens are deprecated. Use OAuth instead."
echo ""
echo "🔑 Neotoma MCP Authentication Helper"
echo ""
echo "RECOMMENDED: Use OAuth for secure, long-lived connections:"
echo "  1. Go to Neotoma web UI → MCP Setup"
echo "  2. Click 'OAuth Connection' tab"
echo "  3. Follow the OAuth flow to create a connection"
echo "  4. Use connection ID in your MCP config (NEOTOMA_CONNECTION_ID)"
echo ""
echo "For legacy session token approach (deprecated), you have two options:"
echo ""
echo "Option 1: Use the Web UI (Recommended)"
echo "  1. Open http://localhost:5195 in your browser"
echo "  2. Sign in if needed"
echo "  3. Click 'MCP Setup' button in the top right"
echo "  4. Go to 'Session Token' tab"
echo "  5. Click 'Copy' to copy your token"
echo ""
echo "Option 2: Use Browser Console"
echo "  1. Open http://localhost:5195 in your browser"
echo "  2. Sign in if needed"
echo "  3. Open browser DevTools (F12 or Cmd+Option+I)"
echo "  4. Go to Console tab"
echo "  5. Run this command:"
echo ""
echo "     const { data: { session } } = await supabase.auth.getSession();"
echo "     console.log('Token:', session?.access_token);"
echo "     navigator.clipboard.writeText(session?.access_token || '');"
echo ""
echo "  6. The token will be logged and copied to clipboard"
echo ""
echo "After getting your token:"
echo "  1. Open .cursor/mcp.json"
echo "  2. Update the NEOTOMA_SESSION_TOKEN value with your full token"
echo "  3. Restart Cursor to apply changes"
echo ""
echo "To validate your token format (should be a long JWT string):"
echo "  - JWT tokens start with 'eyJ' and contain three parts separated by dots"
echo "  - Example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
echo ""
