#!/usr/bin/env tsx
/**
 * Writes `docs/site/generated/route_inventory.json` and `ROUTE_INVENTORY.md`
 * classifying MainApp routes (static MDX pilot vs redirects vs dynamic vs other).
 *
 * Run: tsx scripts/mdx_site_route_inventory.ts
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const mainAppPath = path.join(repoRoot, "frontend/src/components/MainApp.tsx");
const pagesDir = path.join(repoRoot, "docs/site/pages");
const outDir = path.join(repoRoot, "docs/site/generated");

function extractAppRoutePaths(): string[] {
  const source = fs.readFileSync(mainAppPath, "utf-8");
  const routesMatch = source.match(
    /const APP_ROUTES:\s*readonly\s+AppRoute\[\]\s*=\s*\[([^]*?)\n\];/,
  );
  if (!routesMatch) throw new Error("Could not locate APP_ROUTES array in MainApp.tsx");
  const block = routesMatch[1];
  const paths: string[] = [];
  const re = /path:\s*"([^"]+)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(block)) !== null) {
    paths.push(m[1]);
  }
  return paths;
}

function mdxBackedPaths(): Set<string> {
  const out = new Set<string>();
  if (!fs.existsSync(pagesDir)) return out;
  const walk = (dir: string) => {
    for (const name of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, name.name);
      if (name.isDirectory()) walk(p);
      else if (name.name.endsWith(".meta.json")) {
        const raw = JSON.parse(fs.readFileSync(p, "utf-8")) as { path?: string };
        if (typeof raw.path === "string") out.add(raw.path);
      }
    }
  };
  walk(pagesDir);
  return out;
}

function classify(
  routePath: string,
  mdxPaths: Set<string>,
): "static_mdx" | "dynamic" | "other" {
  if (routePath.includes(":")) return "dynamic";
  if (mdxPaths.has(routePath)) return "static_mdx";
  return "other";
}

function main() {
  const paths = extractAppRoutePaths();
  const mdxPaths = mdxBackedPaths();

  const rows = paths.map((path) => ({
    path,
    classification: classify(path, mdxPaths),
  }));

  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "route_inventory.json"), JSON.stringify(rows, null, 2), "utf-8");

  const md = [
    "# Site route inventory (generated)",
    "",
    "Generated by `scripts/mdx_site_route_inventory.ts`. Do not hand-edit.",
    "",
    "| Path | Classification |",
    "|------|----------------|",
    ...rows.map((r) => `| \`${r.path}\` | ${r.classification} |`),
    "",
    "## Counts",
    "",
    ...Object.entries(
      rows.reduce<Record<string, number>>((acc, r) => {
        acc[r.classification] = (acc[r.classification] ?? 0) + 1;
        return acc;
      }, {}),
    ).map(([k, v]) => `- **${k}**: ${v}`),
    "",
  ].join("\n");

  fs.writeFileSync(path.join(outDir, "ROUTE_INVENTORY.md"), md, "utf-8");
  console.log(`Wrote ${path.relative(repoRoot, outDir)}/route_inventory.json and ROUTE_INVENTORY.md`);
}

main();
