/**
 * Unit tests for mirror_writeback.ts — disk-to-entity write-back (issue #1776).
 *
 * Covers:
 *   - parseMirrorMarkdown: extracts editable fields, skips managed regions
 *   - parseYamlFrontmatter: handles scalars, arrays, quoted strings
 *   - parseMarkdownSections: ## section parser for entity mode
 *   - extractEntityIdFromFile: reads entity_id from frontmatter
 *   - runMirrorPush:
 *       - blocked by missing allow_disk_writeback flag
 *       - canonical-unchanged → corrections applied
 *       - both-sides-changed → conflict emitted
 *       - dry-run applies nothing
 *       - no base → applies disk state
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import * as path from "node:path";
import * as fs from "node:fs/promises";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";

import {
  parseMirrorMarkdown,
  parseYamlFrontmatter,
  parseMarkdownSections,
  extractEntityIdFromFile,
  runMirrorPush,
  type WritebackApiClient,
} from "../../src/services/mirror_writeback.ts";
import type { MirrorProfile } from "../../src/services/canonical_mirror.ts";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const FRONTMATTER_CONTENT_FILE = `<!-- Do not edit this file directly. Corrections go through \`neotoma corrections create\`, \`neotoma edit <id>\`, or the Neotoma Inspector. This file is regenerated on every relevant write. -->

---
entity_id: ent_abc123
entity_type: plan
schema_version: 1.0
last_observation_at: 2026-06-01T00:00:00Z
observation_count: 5
computed_at: 2026-06-01T00:00:00Z
title: My Plan
status: active
priority: high
tags:
  - feature
  - q3
---

## Overview

This is the plan body.

It has multiple paragraphs.
`;

const ENTITY_MODE_FILE = `<!-- Do not edit this file directly. Corrections go through \`neotoma corrections create\`, \`neotoma edit <id>\`, or the Neotoma Inspector. This file is regenerated on every relevant write. -->

---
entity_id: ent_abc123
entity_type: plan
schema_version: 1.0
last_observation_at: 2026-06-01T00:00:00Z
observation_count: 5
computed_at: 2026-06-01T00:00:00Z
---

# My Plan

## title

My Plan

## status

active

## provenance

| field | observation_id |
| --- | --- |
| title | obs_1 |
`;

function makeProfile(overrides: Partial<MirrorProfile> = {}): MirrorProfile {
  return {
    id: "test-profile",
    entity_type: "plan",
    filter: {},
    output_path: "/tmp/test-output",
    render_mode: "frontmatter_content",
    content_field: "body",
    allow_disk_writeback: true,
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// parseMirrorMarkdown
// ---------------------------------------------------------------------------

describe("parseMirrorMarkdown — frontmatter_content mode", () => {
  it("extracts user-defined frontmatter fields, skipping managed system fields", () => {
    const profile = makeProfile({ render_mode: "frontmatter_content", content_field: "body" });
    const fields = parseMirrorMarkdown(FRONTMATTER_CONTENT_FILE, profile);

    // User fields present
    expect(fields.title).toBe("My Plan");
    expect(fields.status).toBe("active");
    expect(fields.priority).toBe("high");
    expect(fields.tags).toEqual(["feature", "q3"]);

    // Managed fields NOT present
    expect(fields).not.toHaveProperty("entity_id");
    expect(fields).not.toHaveProperty("entity_type");
    expect(fields).not.toHaveProperty("schema_version");
    expect(fields).not.toHaveProperty("last_observation_at");
    expect(fields).not.toHaveProperty("observation_count");
    expect(fields).not.toHaveProperty("computed_at");
  });

  it("captures the body after frontmatter as the content_field", () => {
    const profile = makeProfile({ render_mode: "frontmatter_content", content_field: "body" });
    const fields = parseMirrorMarkdown(FRONTMATTER_CONTENT_FILE, profile);

    expect(fields.body).toContain("## Overview");
    expect(fields.body).toContain("This is the plan body.");
  });

  it("strips the DO NOT EDIT header comment before parsing", () => {
    const profile = makeProfile({ render_mode: "frontmatter_content" });
    const fields = parseMirrorMarkdown(FRONTMATTER_CONTENT_FILE, profile);
    // If the DO NOT EDIT comment were not stripped, the frontmatter would not be found.
    expect(fields.title).toBe("My Plan");
  });

  it("returns empty body when no content after frontmatter", () => {
    const fileWithoutBody = `---
entity_id: ent_abc123
entity_type: plan
schema_version: 1.0
title: Empty
---
`;
    const profile = makeProfile({ render_mode: "frontmatter_content", content_field: "body" });
    const fields = parseMirrorMarkdown(fileWithoutBody, profile);
    expect(fields.title).toBe("Empty");
    expect(fields.body).toBeUndefined();
  });
});

describe("parseMirrorMarkdown — entity mode", () => {
  it("extracts ## section fields, skipping provenance", () => {
    const profile = makeProfile({ render_mode: "entity" });
    const fields = parseMirrorMarkdown(ENTITY_MODE_FILE, profile);

    expect(fields.title).toBe("My Plan");
    expect(fields.status).toBe("active");

    // Managed frontmatter fields not present
    expect(fields).not.toHaveProperty("entity_id");
    expect(fields).not.toHaveProperty("schema_version");

    // Provenance section should be skipped
    expect(fields).not.toHaveProperty("provenance");
  });
});

describe("parseMirrorMarkdown — content_only mode", () => {
  it("returns the whole file as the content field", () => {
    const content = "# Hello\n\nThis is the content.";
    const profile = makeProfile({ render_mode: "content_only", content_field: "notes" });
    const fields = parseMirrorMarkdown(content, profile);
    expect(fields.notes).toBe(content.trimEnd());
  });
});

// ---------------------------------------------------------------------------
// parseYamlFrontmatter
// ---------------------------------------------------------------------------

describe("parseYamlFrontmatter", () => {
  it("parses simple scalar key-value pairs", () => {
    const yaml = `title: My Plan\nstatus: active\npriority: high`;
    const result = parseYamlFrontmatter(yaml);
    expect(result.title).toBe("My Plan");
    expect(result.status).toBe("active");
    expect(result.priority).toBe("high");
  });

  it("parses boolean values", () => {
    const yaml = `active: true\narchived: false`;
    const result = parseYamlFrontmatter(yaml);
    expect(result.active).toBe(true);
    expect(result.archived).toBe(false);
  });

  it("parses numeric values", () => {
    const yaml = `count: 42\nscore: 3.14`;
    const result = parseYamlFrontmatter(yaml);
    expect(result.count).toBe(42);
    expect(result.score).toBe(3.14);
  });

  it("parses simple list values", () => {
    const yaml = `tags:\n  - feature\n  - q3\n  - backend`;
    const result = parseYamlFrontmatter(yaml);
    expect(result.tags).toEqual(["feature", "q3", "backend"]);
  });

  it("handles null values", () => {
    const yaml = `title: null\nauthor: ~`;
    const result = parseYamlFrontmatter(yaml);
    expect(result.title).toBeNull();
    expect(result.author).toBeNull();
  });

  it("skips blank lines and comments", () => {
    const yaml = `# comment\ntitle: Test\n\nstatus: active`;
    const result = parseYamlFrontmatter(yaml);
    expect(result.title).toBe("Test");
    expect(result.status).toBe("active");
  });
});

// ---------------------------------------------------------------------------
// parseMarkdownSections
// ---------------------------------------------------------------------------

describe("parseMarkdownSections", () => {
  it("extracts ## sections as fields", () => {
    const body = `## title\n\nMy Plan\n\n## status\n\nactive\n`;
    const result = parseMarkdownSections(body);
    expect(result.title).toBe("My Plan");
    expect(result.status).toBe("active");
  });

  it("parses JSON code blocks", () => {
    const body = `## metadata\n\n\`\`\`json\n{"key": "value"}\n\`\`\`\n`;
    const result = parseMarkdownSections(body);
    expect(result.metadata).toEqual({ key: "value" });
  });

  it("parses list items from bullet format", () => {
    const body = `## tags\n\n- feature\n- q3\n`;
    const result = parseMarkdownSections(body);
    expect(result.tags).toEqual(["feature", "q3"]);
  });

  it("returns null for _(empty)_ sentinel", () => {
    const body = `## description\n\n_(empty)_\n`;
    const result = parseMarkdownSections(body);
    expect(result.description).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// extractEntityIdFromFile
// ---------------------------------------------------------------------------

describe("extractEntityIdFromFile", () => {
  it("extracts entity_id from frontmatter", () => {
    const id = extractEntityIdFromFile(FRONTMATTER_CONTENT_FILE);
    expect(id).toBe("ent_abc123");
  });

  it("returns null when no frontmatter present", () => {
    const content = "# No frontmatter here\n\nJust content.";
    expect(extractEntityIdFromFile(content)).toBeNull();
  });

  it("returns null when entity_id is missing from frontmatter", () => {
    const content = "---\ntitle: Test\n---\n";
    expect(extractEntityIdFromFile(content)).toBeNull();
  });

  it("handles the DO NOT EDIT header before frontmatter", () => {
    const content = `<!-- Do not edit this file directly. -->\n\n---\nentity_id: ent_xyz\ntitle: Test\n---\n`;
    expect(extractEntityIdFromFile(content)).toBe("ent_xyz");
  });
});

// ---------------------------------------------------------------------------
// runMirrorPush — behavioral tests
// ---------------------------------------------------------------------------

describe("runMirrorPush", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(path.join(tmpdir(), "neotoma-mirror-push-"));
  });

  afterEach(() => {
    try {
      rmSync(tmpDir, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  });

  function makeMockApi(overrides: Partial<WritebackApiClient> = {}): WritebackApiClient {
    const defaultGet = vi.fn().mockResolvedValue({
      data: {
        entity_type: "plan",
        snapshot: { title: "My Plan", status: "active", priority: "high" },
      },
      error: null,
      response: { status: 200 },
    });
    const defaultPost = vi.fn().mockResolvedValue({ data: { success: true }, error: null });
    return {
      GET: (overrides.GET as WritebackApiClient["GET"]) ?? defaultGet,
      POST: (overrides.POST as WritebackApiClient["POST"]) ?? defaultPost,
    };
  }

  it("blocks push when allow_disk_writeback is not set", async () => {
    const profile = makeProfile({ allow_disk_writeback: false, output_path: tmpDir });
    const api = makeMockApi();
    const result = await runMirrorPush(profile, api);

    expect(result.errors.length).toBeGreaterThan(0);
    expect(result.errors[0].message).toContain("allow_disk_writeback");
    expect(result.corrections_applied).toBe(0);
  });

  it("blocks push when allow_disk_writeback is undefined (default false)", async () => {
    const profile = makeProfile({ output_path: tmpDir });
    delete (profile as Partial<MirrorProfile>).allow_disk_writeback;
    const api = makeMockApi();
    const result = await runMirrorPush(profile, api);

    expect(result.errors.length).toBeGreaterThan(0);
    expect(result.errors[0].message).toContain("allow_disk_writeback");
    expect(result.corrections_applied).toBe(0);
  });

  it("applies corrections when canonical is unchanged and disk was edited (no prior base)", async () => {
    const profile = makeProfile({
      allow_disk_writeback: true,
      output_path: tmpDir,
      render_mode: "frontmatter_content",
      content_field: "body",
    });

    // Write a mirror file with an edited title.
    const diskContent = `---
entity_id: ent_test01
entity_type: plan
schema_version: 1.0
title: Edited Title
status: active
---

My body content.
`;
    const filePath = path.join(tmpDir, "my-plan.md");
    await fs.writeFile(filePath, diskContent, "utf8");

    const postMock = vi.fn().mockResolvedValue({ data: { success: true }, error: null });
    const getMock = vi.fn().mockResolvedValue({
      data: {
        entity_type: "plan",
        snapshot: { title: "Original Title", status: "active" },
      },
      error: null,
      response: { status: 200 },
    });
    const api = makeMockApi({ GET: getMock, POST: postMock });

    const result = await runMirrorPush(profile, api);

    expect(result.errors).toHaveLength(0);
    expect(result.conflicts).toHaveLength(0);
    expect(result.corrections_applied).toBeGreaterThan(0);

    // The correction should be for the "title" field.
    const titleCorrection = postMock.mock.calls.find(
      (call) => (call[1] as { body: { field: string } }).body.field === "title"
    );
    expect(titleCorrection).toBeDefined();
    if (titleCorrection) {
      expect((titleCorrection[1] as { body: { value: unknown } }).body.value).toBe("Edited Title");
    }
  });

  it("applies corrections when canonical unchanged since base (3-way: canonical==base)", async () => {
    const profile = makeProfile({
      allow_disk_writeback: true,
      output_path: tmpDir,
      render_mode: "frontmatter_content",
      content_field: "body",
    });

    // Simulate a base that matches canonical — disk has been edited.
    const canonicalSnapshot = { title: "Original Title", status: "active" };
    const diskContent = `---
entity_id: ent_test02
entity_type: plan
schema_version: 1.0
title: Disk Edited Title
status: active
---

Body.
`;
    const filePath = path.join(tmpDir, "my-plan.md");
    await fs.writeFile(filePath, diskContent, "utf8");

    // Write a base map where snapshot == canonical (no prior edit).
    const baseDir = path.join(tmpDir, ".neotoma-mirror-base");
    await fs.mkdir(baseDir, { recursive: true });
    const baseMap = {
      "my-plan.md": {
        content_hash: "aabbcc",  // different from disk (disk changed)
        snapshot: canonicalSnapshot,
      },
    };
    await fs.writeFile(path.join(baseDir, "basemap.json"), JSON.stringify(baseMap), "utf8");

    let callCount = 0;
    const getMock = vi.fn().mockImplementation(() => {
      callCount++;
      return Promise.resolve({
        data: { entity_type: "plan", snapshot: canonicalSnapshot },
        error: null,
        response: { status: 200 },
      });
    });
    const postMock = vi.fn().mockResolvedValue({ data: { success: true }, error: null });
    const api = makeMockApi({ GET: getMock, POST: postMock });

    const result = await runMirrorPush(profile, api);

    expect(result.conflicts).toHaveLength(0);
    expect(result.corrections_applied).toBeGreaterThan(0);
    // Title correction should apply the disk value.
    const titleCall = postMock.mock.calls.find(
      (c) => (c[1] as { body: { field: string } }).body.field === "title"
    );
    expect(titleCall).toBeDefined();
  });

  it("emits a conflict when both disk and canonical changed since base", async () => {
    const profile = makeProfile({
      allow_disk_writeback: true,
      output_path: tmpDir,
      render_mode: "frontmatter_content",
      content_field: "body",
    });

    const diskContent = `---
entity_id: ent_conflict01
entity_type: plan
schema_version: 1.0
title: Disk Changed
status: active
---

Body.
`;
    const filePath = path.join(tmpDir, "conflict.md");
    await fs.writeFile(filePath, diskContent, "utf8");

    // Base has original title, canonical also changed to something else.
    const baseDir = path.join(tmpDir, ".neotoma-mirror-base");
    await fs.mkdir(baseDir, { recursive: true });
    const baseMap = {
      "conflict.md": {
        content_hash: "original-hash",
        snapshot: { title: "Original", status: "active" },
      },
    };
    await fs.writeFile(path.join(baseDir, "basemap.json"), JSON.stringify(baseMap), "utf8");

    const getMock = vi.fn().mockResolvedValue({
      data: {
        entity_type: "plan",
        snapshot: { title: "Canonical Changed", status: "active" },
      },
      error: null,
      response: { status: 200 },
    });
    const postMock = vi.fn().mockResolvedValue({ data: { success: true }, error: null });
    const api = makeMockApi({ GET: getMock, POST: postMock });

    const result = await runMirrorPush(profile, api);

    expect(result.conflicts.length).toBeGreaterThan(0);
    const titleConflict = result.conflicts.find((c) => c.field === "title");
    expect(titleConflict).toBeDefined();
    if (titleConflict) {
      expect(titleConflict.base_value).toBe("Original");
      expect(titleConflict.disk_value).toBe("Disk Changed");
      expect(titleConflict.canonical_value).toBe("Canonical Changed");
    }
    // No corrections should be applied when there are conflicts.
    expect(postMock).not.toHaveBeenCalled();
    expect(result.corrections_applied).toBe(0);
  });

  it("dry-run mode applies nothing and reports corrections_dry_run", async () => {
    const profile = makeProfile({
      allow_disk_writeback: true,
      output_path: tmpDir,
      render_mode: "frontmatter_content",
      content_field: "body",
    });

    const diskContent = `---
entity_id: ent_dryrun01
entity_type: plan
schema_version: 1.0
title: Dry Run Edited
status: active
---

Body.
`;
    const filePath = path.join(tmpDir, "dryrun.md");
    await fs.writeFile(filePath, diskContent, "utf8");

    const postMock = vi.fn().mockResolvedValue({ data: { success: true }, error: null });
    const getMock = vi.fn().mockResolvedValue({
      data: {
        entity_type: "plan",
        snapshot: { title: "Original", status: "active" },
      },
      error: null,
      response: { status: 200 },
    });
    const api = makeMockApi({ GET: getMock, POST: postMock });

    const result = await runMirrorPush(profile, api, { dry_run: true });

    // No actual POST calls.
    expect(postMock).not.toHaveBeenCalled();
    expect(result.corrections_applied).toBe(0);
    expect(result.corrections_dry_run).toBeGreaterThan(0);
    expect(result.conflicts).toHaveLength(0);
  });

  it("no-op when disk matches canonical (nothing changed)", async () => {
    const profile = makeProfile({
      allow_disk_writeback: true,
      output_path: tmpDir,
      render_mode: "frontmatter_content",
      content_field: "body",
    });

    // Disk and canonical are identical.
    const diskContent = `---
entity_id: ent_noop01
entity_type: plan
schema_version: 1.0
title: Same Title
status: active
---

Same body.
`;
    const filePath = path.join(tmpDir, "noop.md");
    await fs.writeFile(filePath, diskContent, "utf8");

    const postMock = vi.fn().mockResolvedValue({ data: { success: true }, error: null });
    const getMock = vi.fn().mockResolvedValue({
      data: {
        entity_type: "plan",
        snapshot: { title: "Same Title", status: "active", body: "Same body." },
      },
      error: null,
      response: { status: 200 },
    });
    const api = makeMockApi({ GET: getMock, POST: postMock });

    const result = await runMirrorPush(profile, api);

    expect(postMock).not.toHaveBeenCalled();
    expect(result.corrections_applied).toBe(0);
    expect(result.conflicts).toHaveLength(0);
    expect(result.errors).toHaveLength(0);
  });
});
